//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoeval_progplan
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public string ProgPlan { get; set; }
    }
}
